//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaziklikker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WikiRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WikiRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaziklikker.WikiRes", typeof(WikiRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bank is a special feature in Kaziklikker, you can find the bank in the bottom-left of your screen. You can click the buttons &apos;deposit&apos; and &apos;withdraw&apos; to deposit and withdraw your money from the bank.
        ///
        ///Every time the counter hits 0, your money is divided by ten and then multiplied by your interest rate.
        ///
        ///Some examples:
        ///1000 ÷ 10 × 11 = 1100
        ///5000 ÷ 10 × 12 = 6000
        ///
        ///To raise your interest rate, you can buy the &apos;bank&apos; upgrade. This is further explained on the upgrades page.
        ///
        ///Your bank account might [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Kaziklikker, on this page, you will learn the basics of the game.
        ///
        ///The money you currently have is shown on the top-left corner of your the game window. To gain money, you have to click on the money in the middle of your screen. Once you clicked enough and made yourself some money, you can buy a &apos;clicker&apos;. When you bought the clicker, your CPS counter goes up by 1. The CPS is added to your money every second*.
        ///
        ///*generally speaking.
        /// </summary>
        internal static string basics {
            get {
                return ResourceManager.GetString("basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming features (3.3)
        ///-Achievements
        ///-Better cheats
        ///-Secret stuff
        ///
        ///Kaziklikker version 3.2.2 (02-09-2016)
        ///-Random colours
        ///*Wiki is now free
        ///*improvements
        ///
        ///Kaziklikker version 3.2.1 (15-02-2016)
        ///-Removed the sell mode
        ///*improvements
        ///
        ///Kaziklikker version 3.2 (15-02-2016)
        ///+Added an FPS counter
        ///+Added the experience system
        ///+Added XP-Shop
        ///+Added the firewall upgrade
        ///+Added colour to the shop
        ///+Added a &apos;clean&apos; mode
        ///+Added changelog
        ///*Reworked the saving system
        ///*Reworked the bank
        ///*Readded the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheats in Kaziklikker are explained on this page. You gain cheat codes by buying something in the shop 500 times. But, when you cheat, your game won&apos;t get saved..
        /// </summary>
        internal static string cheat {
            get {
                return ResourceManager.GetString("cheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaziklikker, a game made by Rico de Jong.
        ///
        ///Testers: Axes Denite and melle.ellem.
        ///
        ///Programs used: Microsoft Visual Studio 2015 Community edition, Paint.net and Audacity..
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page, we&apos;ll talk about the experience system of Kaziklikkker. You can see how much experience you currently have by looking at the top of your screen. You gain XP by completing certain actions. There are two things you can do with experience: you can save it to buy things from the XP-Shop, or you can convert it to money. You can see the course next to the &apos;convert&apos; button..
        /// </summary>
        internal static string experience {
            get {
                return ResourceManager.GetString("experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the wiki, the place to learn! to navigate to a page, just click on one of the pages on the left.
        ///
        ///The Stars on the right tell you how difficult a topic is.
        ///1: beginner
        ///2: advanced
        ///3: pro.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Kaziklikker, particularly the late game, numbers tend to be very big. In order to still make them readable, the numbers are shortened. Here is a list of all the abbreviations used.
        ///
        ///K (thousands)
        ///1K = 1000
        ///
        ///M (millions)
        ///1M = 1000K = 1000000
        ///
        ///B (billions)
        ///1B = 1000M = 1000000K = 1000000000
        ///
        ///T (trillions)
        ///1T = 1000B = 1000000M = 1000000000K = 1000000000000
        ///
        ///Qa (quadrillions)
        ///1Qa = 1000T = 1000000B = 1000000000M = 1000000000000K = 1000000000000000
        ///
        ///Qi (quintillions)
        ///1Qi = 1000Qa = 1000000T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string largenumber {
            get {
                return ResourceManager.GetString("largenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lottery can be accessed on the right side of the screen.  The jackpot and price of a ticket are shown next to the buttons. When you buy a ticket, the game randomly decides if you&apos;ve won. The most expensive lottery &apos;exprice&apos; has a twist to it, there is a ten percent chance that your game will be reset,  this can&apos;t be undone..
        /// </summary>
        internal static string lottery {
            get {
                return ResourceManager.GetString("lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shop in Kaziklikker is located on the right-side of your screen. Every item available in Kaziklikker is listed there. The number left to the button shows the amount of an item, the number on the right shows the price of the item. When a button is gray, it means you don&apos;t have enough money, to buy that item. Here is an overview of every item in the shop.
        ///
        ///Name: Clicker
        ///Default price: 25
        ///Default speed: 1
        ///CPS upgrade  : +1
        ///
        ///Name: Farm
        ///Default price: 125
        ///Default speed: 3
        ///CPS upgrade  : +3
        ///
        ///Name: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As well as a shop, there is also an upgrades shop in Kaziklikker. In this shop, however, you can buy upgrades. On this page, you can find an explanation of all upgrades available in this shop.
        ///
        ///The &apos;cheap&apos; upgrade makes everything cheaper. For example, a farm costs 150 before the upgrade, and only costs 125 after the upgrade.
        ///
        ///The &apos;clicking speed&apos; upgrade adds 10 to your original clicking speed. You might think to yourself that that&apos;s not a lot, but after it doubles again, and  again. It really makes a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
    }
}
